### ISSUE TITLE
"PTP time" used in the code

### ISSUE THREAD

**Issue by kierank** [aws/aws-cdi-sdk#2] opened 2020-09-16 17:54 UTC
The term "PTP time" appears to be used in the code, but none of the OS APIs use any form of PTP-capable API.

**Comment by danengholm** [comment] 2020-09-17 17:22
Kieran,

The AWS CDI SDK transparently carries time stamps with every payload. The SDK does not modify or even look at its value with the exception of the optional receive buffer (see below). The value provided with a transmitted payload is available in the structure passed to the application's registered receive payload callback function.

For interoperability, this PTP value should follow the specifications set out in ST 2059. Doing so will allow downstream devices to synchronize streams from multiple sources for the purposes of switching, failover, and processing.

The application is responsible for providing timestamps with adequate accuracy and precision. Properly configured AWS EC2 instances have system clocks with NTP precision and accuracy under 1 ms which should be sufficient for 60 frame per second video. For example, the application can call CdiOsGetUtcTime​() and convert the returned timespec structure to a CdiPtpTimestamp​ to give to a transmit payload function. Other sources of time are possible.​

The optional receive buffer uses the timestamp in received payloads to effect a buffer to decrease jitter caused by transport over the network. By default, it is not engaged and receive payloads are delivered to the application's callback function as soon as they are fully assembled from their constituent packets. Applications are free to implement their own receive buffering schemes which may be more sophisticated.

**Comment by kierank** [comment] 2020-09-17 17:31
I see no code to convert between UTC and the TAI that is required for PTP (leap seconds) here, not to mention the whole can of worms with leap second smears:
https://github.com/aws/aws-cdi-sdk/blob/90074c5820c86b444fac2276452f654d67d467f8/src/test_minimal/test_minimal_transmitter.c#L489

**Comment by danengholm** [comment] 2020-09-17 17:53
Kieran,

We need to research this topic in depth and will update the issue when we have an answer to your question.

**Comment by mhhen** [comment] 2020-09-22 15:16
Leap second events are very, very rare. The next event could be in June 2021. We do intend to add an API to convert between UTC/TAI and add logic to handle leap second smears.

**Comment by kierank** [comment] 2020-09-22 15:32
You still need to handle the TAI-UTC difference if you wanted CDI to interoperate with other PTP devices (personally I don't see the point and would just use UTC and forget about PTP altogether)

**Comment by mhhen** [comment] 2020-09-23 21:23
Thank you for providing additional details. We are reopening this issue and will provide updates here. Thanks again, and if there’s any other information that you want to share, we’ll take the feedback as we work on resolving this.

**Comment by pierremestrez1976** [comment] 2021-04-07 15:24
Does the AWS EC2 environnent provide an accurate PTP between instances ?

**Comment by mhhen** [comment] 2021-04-09 15:01
No. The Network Time Protocol (NTP) is currently being used. I found some additional details about NTP here: https://aws.amazon.com/blogs/mt/manage-amazon-ec2-instance-clock-accuracy-using-amazon-time-sync-service-and-amazon-cloudwatch-part-1/

**Closed as completed** 2023-01-23 18:35 UTC
