### ISSUE TITLE
Issue when establishing a connection

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#6] opened 2020-10-02 18:33 UTC
We've been working on an sample application which we started using a pre-release version of the CDI SDK. We've now updated it to use the latest version and are having some issues while establishing a connection that we hadn't experienced with the pre-release. It seems that under certain conditions, when a connection is attempted, the connection state change callback in the receiver is invoked with an initial `kCdiConnectionStatusDisconnected` status, followed by a second call again with `kCdiConnectionStatusDisconnected`. The connection is then dropped. We suspect that it's some sort of race condition and though we are not sure about this, seems to happen when the transmitter is started before the receiver.

We observe this running both receiver and transmitter locally using the Socket Libfabric adapter. We've yet to try the same in EC2 and EFA. 

Note that we can also reproduce the same behavior with the **test_minimal_receiver** and **test_minimal_transmitter**, which we modified to use the Socket Libfabric adapter and to display a diagnostic message in the connection state change callback with the connection status based on the received `status_code`.

### Steps to reproduce (on a Windows machine)
Since this issue does not occur every time,the best way we've found to reproduce it more frequently is to start the transmitter and receiver in a single step using the following command line:

```
START cdi_test_min_rx --rx AVM --local_ip 127.0.0.1 --dest_port 2000 --payload_size 2050560 --num_transactions 500 & cdi_test_min_tx --tx AVM --local_ip 127.0.0.1 --dest_port 2000 --remote_ip 127.0.0.1 --payload_size 2050560 --num_transactions 500 --rate 24/1 --tx_timeout 50000
```
This is the output from the receiver and trasmitter:
### RECEIVER OUTPUT
```
[2020-10-02T14:41:13-03:00] [main:236] Initializing test.
[2020-10-02T14:41:13-03:00] [RxCreateInternal:718] Creating Rx connection. Protocol[AVM] Destination Port[2000] Name[]
[2020-10-02T14:41:13-03:00] [RxCreateInternal:734] Rx connection is unnamed. Created name[dest2000]
[2020-10-02T14:41:13-03:00] [ProbeRxControlMessageFromEndpoint:230] Creating new Rx endpoint stream ID[-1].
[2020-10-02T14:41:13-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:7d1:c0a8:3001::-0000].
[2020-10-02T14:41:13-03:00] [EndpointManagerRxCreateEndpoint:872] Successfully created Rx stream endpoint. Name[dest2000]
[2020-10-02T14:41:13-03:00] [RxCreateInternal:838] Successfully created Rx connection. Name[dest2000]
[2020-10-02T14:41:13-03:00] [main:304] Waiting to establish connection with remote target...
[2020-10-02T14:41:13-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:7d1:c0a8:3001::-0000].
[2020-10-02T14:41:13-03:00] [EndpointManagerRxCreateEndpoint:872] Successfully created Rx stream endpoint. Name[dest2000]
[2020-10-02T14:41:13-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:7d1:c0a8:3001::-0000].
[2020-10-02T14:41:16-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:7d1:c0a8:3001::-0000].

############
CONNECTION STATE: DISCONNECTED
############
[2020-10-02T14:41:16-03:00] [main:304] Waiting to establish connection with remote target...
[2020-10-02T14:41:17-03:00] [EndpointManagerEndpointDestroy:916] Destroy endpoint stream ID[-1].

############
CONNECTION STATE: DISCONNECTED
############
[2020-10-02T14:41:17-03:00] [main:304] Waiting to establish connection with remote target...
```
### TRANSMITTER OUTPUT
```
[2020-10-02T14:41:13-03:00] [main:377] Initializing test.
[2020-10-02T14:41:13-03:00] [TxCreateConnection:420] Tx connection is unnamed. Created name[127.0.0.1:2000]
[2020-10-02T14:41:13-03:00] [TxCreateConnection:434] Creating Tx connection. Protocol[AVM] Destination IP[127.0.0.1] Destination Port[2000] Name[127.0.0.1:2000]
[2020-10-02T14:41:13-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:c53a:7f00:1::-0000].
[2020-10-02T14:41:13-03:00] [EndpointManagerTxCreateEndpoint:809] Successfully created Tx stream ID[-1] endpoint. Name[127.0.0.1:2000]
[2020-10-02T14:41:13-03:00] [main:446] Waiting to establish connection with remote target...
[2020-10-02T14:41:13-03:00] [ProbeTxControlProcessPacket:209] Probe Tx stream ID[-1] using remote EFA device GID[200:7d1:c0a8:3001::-0000].
[2020-10-02T14:41:16-03:00] ERROR: [ProbeTxControlProcessProbeState:331] Control handshake was successful. However, an insufficient number of probe packets were received. Verify the security group settings are correctly configured. See the CDI SDK Install and Setup Guide for proper security group configuration.
[2020-10-02T14:41:16-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:c57c:7f00:1::-0000].
[2020-10-02T14:41:16-03:00] [LibFabricEndpointOpen:266] Using local EFA device GID[200:c58d:7f00:1::-0000].
[2020-10-02T14:41:16-03:00] [ProbeTxControlProcessPacket:209] Probe Tx stream ID[-1] using remote EFA device GID[200:7d1:c0a8:3001::-0000].
############
CONNECTION STATE: CONNECTED
############
[2020-10-02T14:41:16-03:00] [main:450] Connected. Sending payloads...
[2020-10-02T14:41:17-03:00] [CdiAdapterEnqueueSendPackets:694] Tx packet queue[Tx Packet CdiSinglyLinkedList Queue] full.
[2020-10-02T14:41:17-03:00] [CdiAdapterEnqueueSendPackets:694] Tx packet queue[Tx Packet CdiSinglyLinkedList Queue] full.
```

Sometimes, the receiver output also includes an assertion
```
############
CONNECTION STATE: DISCONNECTED
############
[2020-10-02T14:45:08-03:00] [main:304] Waiting to establish connection with remote target...
[2020-10-02T14:45:08-03:00] [EndpointManagerEndpointDestroy:916] Destroy endpoint stream ID[-1].

############
CONNECTION STATE: DISCONNECTED
############
[2020-10-02T14:45:08-03:00] [main:304] Waiting to establish connection with remote target...
[2020-10-02T14:45:08-03:00] FATAL ERROR: [CdiPoolDestroy:348] Pool[EfaRxEndpoint CdiSglEntry Pool] to be destroyed has[60] entries still in use.
Assertion failed: false, file C:\Users\FernandoTubio\source\repos\aws\aws-cdi-sdk\src\common\src\pool.c, line 349
```

Any suggestions?

**Comment by mhhen** [comment] 2020-10-05 17:05
Thank you for providing all the detailed information. We started investigating the problem and were able to reproduce it using the minimal Tx/Rx test applications with the modifications you suggested (use socket adapter) withing a few minutes. However, we were not able to reproduce the problem using the EFA adapter after running tests for several hours. We will continue to investigate and update this issue with progress and findings. If there is any additional detail that might be helpful, please update this issue with the information.

**Comment by mhhen** [comment] 2020-10-05 18:24
The problem appears to be specific to windows (release and debug builds). We have not been able to reproduce the problem on Linux.

**Comment by f2bo** [comment] 2020-10-05 18:26
Thanks. It's good to know that this isn't an issue with the EFA adapter. We'll report if we see anything different once we start testing in EC2. Unfortunately, we are hitting this issue quite frequently during development (in Windows), so a solution would be welcome.

Just a couple of things to add. The problem seems to go away when you insert a pause between both commands in the script above (e.g. START cdi_test_min_rx ... & **PAUSE** & cdi_test_min_tx ....) so that the transmitter isn't started until you press a key. An to reiterate, we hadn't noticed this problem before with the pre-release SDK and the socket adapter. I'm not sure whether this helps to narrow down the cause.

**Comment by trevorheaws** [comment] 2020-11-14 01:16
Thank you for your patience on this issue. We have merged a code change to mainline which has resolved the socket libfabric connection issue in our testing. Please let us know if [commit 4fb2654](https://github.com/aws/aws-cdi-sdk/commit/4fb2654cef8c5527eab36891fffc6388720839c8) fails to resolve the connection issue that you were seeing.

**Comment by f2bo** [comment] 2020-11-16 22:49
Hi Trevor,

Yes. This appears to have resolved the problem. I haven't seen it fail since I applied your changes.  I now have another problem when opening two separate connections (sorry), but I'll open a separate issue to report that one.  Let me know if you want me to close this issue.

Thanks!

**Closed as completed** 2020-11-16 22:52 UTC
